# file_name: workout_session.py

"""Runtime coordinator for a workout session.

Implements ``docs/02_runtime/18_WORKOUT_SESSION_ENGINE.md``. The engine
coordinates exercises, sets, repetitions, timers and rest periods, and publishes
``WorkoutState``.

It deliberately does none of the analysis: it never validates posture, never
calculates joint angles, never counts repetitions itself and never touches
MediaPipe. Repetitions arrive as ``RepUpdate`` contracts.

Time is supplied by an injected clock rather than read from the wall clock
directly, which keeps the engine deterministic, testable and independent of the
UI as required by section 21.

Elapsed time accumulates only while a session is running, so pausing freezes
every timer without any timestamp arithmetic.
"""

import logging
import time
from typing import Callable

from app.engines.session.runtime_contracts import (
    TERMINAL_STATUSES,
    RepUpdate,
    SessionSummary,
    WorkoutState,
    WorkoutStatus,
)
from app.engines.workout.workout_plan import WorkoutExercise, WorkoutPlan
from app.shared.exceptions import InvalidSessionStateError, SessionNotActiveError

logger = logging.getLogger(__name__)

Clock = Callable[[], float]
"""A monotonic source of seconds."""


class WorkoutSession:
    """Tracks the execution of one workout plan."""

    def __init__(
        self,
        workout_id: str,
        plan: WorkoutPlan,
        clock: Clock = time.monotonic,
    ) -> None:
        """Create a session in the ``READY`` state.

        Args:
            workout_id: Identifier of the workout being performed. Generated by
                the application layer, not by the engine.
            plan: The workout plan to execute.
            clock: Monotonic time source, injected for determinism in tests.

        Raises:
            InvalidSessionStateError: If the plan contains no exercises.
        """
        if not plan.exercises:
            raise InvalidSessionStateError("Workout plan contains no exercises.")

        self.workout_id = workout_id
        self.plan = plan
        self._clock = clock

        self._status = WorkoutStatus.READY
        self._status_before_pause: WorkoutStatus | None = None

        self._exercise_index = 0
        self._set_number = 1
        self._reps_this_set = 0
        self._holding = False

        self._sets_completed = 0
        self._exercises_completed = 0
        self._reps_completed = 0

        self._workout_seconds = 0.0
        self._exercise_seconds = 0.0
        self._rest_seconds = 0.0
        self._rest_elapsed = 0.0
        self._hold_seconds = 0.0

        self._last_tick = self._clock()
        self._planned_sets = sum(item.sets for item in plan.exercises)

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> WorkoutState:
        """Begin the session.

        Returns:
            The session state after starting.

        Raises:
            InvalidSessionStateError: If the session has already started.
        """
        if self._status is not WorkoutStatus.READY:
            raise InvalidSessionStateError("The workout session has already started.")

        self._last_tick = self._clock()
        self._status = WorkoutStatus.ACTIVE
        logger.info("Workout started.")
        return self.state()

    def pause(self) -> WorkoutState:
        """Suspend the session, freezing every timer.

        Raises:
            InvalidSessionStateError: If the session is not running.
        """
        self._advance()

        if self._status not in (WorkoutStatus.ACTIVE, WorkoutStatus.RESTING):
            raise InvalidSessionStateError("Only a running session can be paused.")

        self._status_before_pause = self._status
        self._status = WorkoutStatus.PAUSED
        logger.info("Workout paused.")
        return self.state()

    def resume(self) -> WorkoutState:
        """Resume a paused session in the state it was suspended from.

        Raises:
            InvalidSessionStateError: If the session is not paused.
        """
        if self._status is not WorkoutStatus.PAUSED:
            raise InvalidSessionStateError("Only a paused session can be resumed.")

        self._last_tick = self._clock()
        self._status = self._status_before_pause or WorkoutStatus.ACTIVE
        self._status_before_pause = None
        logger.info("Workout resumed.")
        return self.state()

    def stop(self) -> WorkoutState:
        """End the session early, preserving progress.

        Raises:
            InvalidSessionStateError: If the session has already finished.
        """
        self._advance()

        if self._status in TERMINAL_STATUSES:
            raise InvalidSessionStateError("The workout session has already finished.")

        self._status = WorkoutStatus.STOPPED
        logger.info("Workout session interrupted.")
        return self.state()

    # ------------------------------------------------------------------
    # Progress
    # ------------------------------------------------------------------

    def record_rep(self, rep_update: RepUpdate) -> WorkoutState:
        """Apply one repetition observation.

        Updates are ignored while resting or paused, so no progress is made
        outside working time. Held exercises ignore repetitions entirely.

        Args:
            rep_update: The observation produced by the Rep Counter Engine.

        Returns:
            The session state after applying the update.

        Raises:
            SessionNotActiveError: If the session has not started or has
                finished.
        """
        self._advance()
        self._require_running()

        if self._status is not WorkoutStatus.ACTIVE:
            return self.state()

        exercise = self._current_exercise
        if exercise is None or exercise.is_hold:
            return self.state()

        if rep_update.rep_completed:
            self._reps_this_set += 1
            self._reps_completed += 1

        if self._reps_this_set >= exercise.repetitions:
            self._complete_set()

        return self.state()

    def record_hold(self, is_holding: bool) -> WorkoutState:
        """Report whether the user is currently holding a held exercise.

        The engine owns the clock for held exercises: a detector receives no
        timing information, so it reports only that the position is being held.

        Args:
            is_holding: Whether the held position is currently maintained.

        Returns:
            The session state after applying the observation.

        Raises:
            SessionNotActiveError: If the session has not started or has
                finished.
        """
        self._advance()
        self._require_running()

        if self._status is not WorkoutStatus.ACTIVE:
            return self.state()

        exercise = self._current_exercise
        if exercise is None or not exercise.is_hold:
            return self.state()

        self._holding = is_holding
        self._complete_hold_if_reached()
        return self.state()

    def refresh(self) -> WorkoutState:
        """Advance timers without reporting progress.

        Called periodically so rest periods end and held sets complete even when
        no other event arrives.
        """
        self._advance()
        return self.state()

    # ------------------------------------------------------------------
    # State
    # ------------------------------------------------------------------

    def state(self) -> WorkoutState:
        """Return a snapshot of the session."""
        exercise = self._current_exercise
        rest_remaining = 0.0
        if self._status is WorkoutStatus.RESTING and exercise is not None:
            rest_remaining = max(0.0, exercise.rest_seconds - self._rest_elapsed)

        return WorkoutState(
            workout_id=self.workout_id,
            status=self._status,
            exercise_slug=exercise.slug if exercise else None,
            exercise_name=exercise.name if exercise else None,
            current_set=self._set_number if exercise else 0,
            total_sets=exercise.sets if exercise else 0,
            remaining_sets=(exercise.sets - self._set_number + 1) if exercise else 0,
            current_rep=self._reps_this_set,
            target_reps=exercise.repetitions if exercise else 0,
            hold_seconds=int(self._hold_seconds),
            target_hold_seconds=exercise.hold_seconds if exercise else 0,
            remaining_exercises=len(self.plan) - self._exercise_index,
            workout_seconds=int(self._workout_seconds),
            exercise_seconds=int(self._exercise_seconds),
            rest_seconds_remaining=int(rest_remaining),
            completion_percentage=self._completion_percentage(),
        )

    def summary(self) -> SessionSummary:
        """Return the session statistics forwarded to the Progress Service."""
        return SessionSummary(
            workout_id=self.workout_id,
            status=self._status,
            exercises_completed=self._exercises_completed,
            exercises_planned=len(self.plan),
            sets_completed=self._sets_completed,
            sets_planned=self._planned_sets,
            reps_completed=self._reps_completed,
            workout_seconds=int(self._workout_seconds),
            rest_seconds=int(self._rest_seconds),
            completion_percentage=self._completion_percentage(),
        )

    @property
    def status(self) -> WorkoutStatus:
        """Return the current lifecycle status."""
        return self._status

    @property
    def is_finished(self) -> bool:
        """Report whether the session has completed or been stopped."""
        return self._status in TERMINAL_STATUSES

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @property
    def _current_exercise(self) -> WorkoutExercise | None:
        """Return the exercise in progress, or ``None`` once the plan is done."""
        if self._exercise_index >= len(self.plan):
            return None
        return self.plan.exercises[self._exercise_index]

    def _require_running(self) -> None:
        """Reject progress reported outside a running session."""
        if self._status is WorkoutStatus.READY:
            raise SessionNotActiveError("The workout session has not started.")
        if self._status in TERMINAL_STATUSES:
            raise SessionNotActiveError("The workout session has finished.")

    def _advance(self) -> None:
        """Accumulate elapsed time into the buckets the current status feeds."""
        now = self._clock()
        delta = max(0.0, now - self._last_tick)
        self._last_tick = now

        if self._status is WorkoutStatus.ACTIVE:
            self._workout_seconds += delta
            self._exercise_seconds += delta
            if self._holding:
                self._hold_seconds += delta
                self._complete_hold_if_reached()
        elif self._status is WorkoutStatus.RESTING:
            self._workout_seconds += delta
            self._exercise_seconds += delta
            self._rest_seconds += delta
            self._rest_elapsed += delta
            self._finish_rest_if_elapsed()

    def _complete_hold_if_reached(self) -> None:
        """Complete the current set once the prescribed hold time is reached."""
        exercise = self._current_exercise
        if exercise is None or not exercise.is_hold:
            return
        if self._hold_seconds >= exercise.hold_seconds:
            self._complete_set()

    def _finish_rest_if_elapsed(self) -> None:
        """Return to work automatically once the rest period ends."""
        exercise = self._current_exercise
        if exercise is None:
            return
        if self._rest_elapsed >= exercise.rest_seconds:
            self._rest_elapsed = 0.0
            self._status = WorkoutStatus.ACTIVE

    def _complete_set(self) -> None:
        """Record a finished set and move the session forward."""
        exercise = self._current_exercise
        if exercise is None:
            return

        self._sets_completed += 1
        self._reps_this_set = 0
        self._hold_seconds = 0.0
        self._holding = False

        if self._set_number < exercise.sets:
            self._set_number += 1
        else:
            self._complete_exercise()
            if self._status is WorkoutStatus.COMPLETED:
                return

        self._begin_rest()

    def _complete_exercise(self) -> None:
        """Record a finished exercise and select the next one."""
        self._exercises_completed += 1
        logger.info("Exercise completed.")

        self._exercise_index += 1
        self._set_number = 1
        self._exercise_seconds = 0.0

        if self._current_exercise is None:
            self._status = WorkoutStatus.COMPLETED
            logger.info("Workout completed.")

    def _begin_rest(self) -> None:
        """Start the rest period that follows a completed set."""
        exercise = self._current_exercise
        self._rest_elapsed = 0.0

        if exercise is None or exercise.rest_seconds <= 0:
            self._status = WorkoutStatus.ACTIVE
            return

        self._status = WorkoutStatus.RESTING

    def _completion_percentage(self) -> float:
        """Return completed sets as a percentage of the planned sets."""
        if self._planned_sets == 0:
            return 0.0
        return round(self._sets_completed / self._planned_sets * 100, 1)
