# file_name: exercise_repository.py

"""SQLAlchemy implementations of the exercise repositories."""

from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.entities.exercise import Exercise, ExerciseResult, ExerciseSession
from app.domain.repositories.exercise_repository import (
    ExerciseRepository,
    ExerciseSessionRepository,
)
from app.domain.value_objects.enums import ExerciseCategory, SessionStatus
from app.infrastructure.database import mappers
from app.infrastructure.database.models import (
    ExerciseModel,
    ExerciseResultModel,
    ExerciseSessionModel,
)

ACTIVE_STATUSES = (str(SessionStatus.CREATED), str(SessionStatus.RUNNING))


class SqlExerciseRepository(ExerciseRepository):
    """Stores exercise metadata in PostgreSQL."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get(self, exercise_id: UUID) -> Exercise | None:
        model = await self._session.get(ExerciseModel, exercise_id)
        return mappers.to_exercise(model) if model else None

    async def get_by_slug(self, slug: str) -> Exercise | None:
        result = await self._session.execute(
            select(ExerciseModel).where(ExerciseModel.slug == slug)
        )
        model = result.scalar_one_or_none()
        return mappers.to_exercise(model) if model else None

    async def list_supported(self) -> tuple[Exercise, ...]:
        result = await self._session.execute(
            select(ExerciseModel)
            .where(ExerciseModel.is_supported.is_(True))
            .order_by(ExerciseModel.category, ExerciseModel.name)
        )
        return tuple(mappers.to_exercise(model) for model in result.scalars())

    async def list_by_category(
        self, category: ExerciseCategory
    ) -> tuple[Exercise, ...]:
        result = await self._session.execute(
            select(ExerciseModel)
            .where(
                ExerciseModel.is_supported.is_(True),
                ExerciseModel.category == str(category),
            )
            .order_by(ExerciseModel.name)
        )
        return tuple(mappers.to_exercise(model) for model in result.scalars())

    async def upsert_many(self, exercises: tuple[Exercise, ...]) -> int:
        """Seed or refresh the library, matching on the stable slug.

        Identifiers are generated by the backend, so an existing row keeps its
        identifier and only its metadata is refreshed. Anything already
        referencing that exercise stays valid.
        """
        written = 0
        for entity in exercises:
            result = await self._session.execute(
                select(ExerciseModel).where(ExerciseModel.slug == entity.slug)
            )
            model = result.scalar_one_or_none()

            if model is None:
                self._session.add(mappers.to_exercise_model(entity))
            else:
                refreshed = mappers.to_exercise_model(entity)
                model.name = refreshed.name
                model.category = refreshed.category
                model.difficulty = refreshed.difficulty
                model.exercise_type = refreshed.exercise_type
                model.movement_type = refreshed.movement_type
                model.equipment = refreshed.equipment
                model.primary_muscles = refreshed.primary_muscles
                model.secondary_muscles = refreshed.secondary_muscles
                model.instructions = refreshed.instructions
                model.is_supported = refreshed.is_supported
                model.updated_at = refreshed.updated_at
            written += 1

        await self._session.flush()
        return written


class SqlExerciseSessionRepository(ExerciseSessionRepository):
    """Stores exercise sessions and their detector output in PostgreSQL."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get(self, session_id: UUID) -> ExerciseSession | None:
        model = await self._session.get(ExerciseSessionModel, session_id)
        return mappers.to_exercise_session(model) if model else None

    async def get_active_for_user(self, user_id: UUID) -> ExerciseSession | None:
        result = await self._session.execute(
            select(ExerciseSessionModel)
            .where(
                ExerciseSessionModel.user_id == user_id,
                ExerciseSessionModel.status.in_(ACTIVE_STATUSES),
            )
            .order_by(ExerciseSessionModel.started_at.desc())
            .limit(1)
        )
        model = result.scalar_one_or_none()
        return mappers.to_exercise_session(model) if model else None

    async def list_for_user(
        self, user_id: UUID, limit: int = 20, offset: int = 0
    ) -> tuple[ExerciseSession, ...]:
        result = await self._session.execute(
            select(ExerciseSessionModel)
            .where(ExerciseSessionModel.user_id == user_id)
            .order_by(ExerciseSessionModel.started_at.desc())
            .limit(limit)
            .offset(offset)
        )
        return tuple(mappers.to_exercise_session(model) for model in result.scalars())

    async def add(self, session: ExerciseSession) -> ExerciseSession:
        model = mappers.to_exercise_session_model(session)
        self._session.add(model)
        await self._session.flush()
        return mappers.to_exercise_session(model)

    async def update(self, session: ExerciseSession) -> ExerciseSession:
        model = await self._session.get(ExerciseSessionModel, session.id)
        if model is None:
            raise ValueError(f"exercise session {session.id} does not exist")

        mappers.apply_exercise_session(model, session)
        await self._session.flush()
        return mappers.to_exercise_session(model)

    async def add_results(self, results: tuple[ExerciseResult, ...]) -> int:
        for entity in results:
            self._session.add(mappers.to_exercise_result_model(entity))
        await self._session.flush()
        return len(results)

    async def list_results(self, session_id: UUID) -> tuple[ExerciseResult, ...]:
        result = await self._session.execute(
            select(ExerciseResultModel)
            .where(ExerciseResultModel.exercise_session_id == session_id)
            .order_by(ExerciseResultModel.frame_timestamp)
        )
        return tuple(mappers.to_exercise_result(model) for model in result.scalars())
