# file_name: identifier.py

"""Entity identifiers.

``docs/07_database/38_IDENTIFIER_STRATEGY.md`` mandates UUID version 7 for every
persistent entity: globally unique, chronologically ordered, generated by the
backend and never by a client, and exposed to APIs as a string.

Python 3.11 has no ``uuid.uuid7``, and the strategy is a hard requirement rather
than a preference, so generation is implemented here to RFC 9562 rather than
taken on as a dependency.

Layout, most significant bit first:

```
48 bits  unix timestamp in milliseconds
 4 bits  version, always 7
12 bits  counter, preserving order within a millisecond
 2 bits  variant, always 0b10
62 bits  random
```
"""

import os
import threading
import time
from uuid import UUID

UUID_VERSION = 7
UUID_VARIANT = 0b10

_TIMESTAMP_BITS = 48
_COUNTER_BITS = 12
_COUNTER_MAX = (1 << _COUNTER_BITS) - 1
_RANDOM_BITS = 62

_lock = threading.Lock()
_last_timestamp_ms = 0
_counter = 0


def new_id() -> UUID:
    """Generate a new UUID version 7.

    Identifiers generated in the same millisecond are still ordered, because the
    counter field increments rather than being random. This preserves the index
    locality the strategy relies on in section 9.

    Returns:
        A UUIDv7 identifier.
    """
    global _last_timestamp_ms, _counter

    with _lock:
        timestamp_ms = time.time_ns() // 1_000_000

        if timestamp_ms > _last_timestamp_ms:
            _last_timestamp_ms = timestamp_ms
            _counter = 0
        else:
            # Same millisecond, or a clock that moved backwards.
            _counter += 1
            if _counter > _COUNTER_MAX:
                # Borrow from the next millisecond rather than repeat a counter.
                _last_timestamp_ms += 1
                _counter = 0
            timestamp_ms = _last_timestamp_ms

        counter = _counter

    value = (timestamp_ms & ((1 << _TIMESTAMP_BITS) - 1)) << 80
    value |= UUID_VERSION << 76
    value |= counter << 64
    value |= UUID_VARIANT << 62
    value |= int.from_bytes(os.urandom(8), "big") & ((1 << _RANDOM_BITS) - 1)

    return UUID(int=value)


def is_valid_id(value: object) -> bool:
    """Report whether a value is a UUID version 7.

    Accepts a ``UUID`` or its string form, since APIs carry identifiers as
    strings.
    """
    candidate = parse_id(value, strict=False)
    return candidate is not None


def parse_id(value: object, strict: bool = True) -> UUID | None:
    """Convert a value into a UUIDv7.

    Args:
        value: A ``UUID`` or a UUID string.
        strict: When true, an invalid value raises. When false, it returns
            ``None``.

    Returns:
        The parsed identifier, or ``None`` when not strict and invalid.

    Raises:
        ValueError: If the value is not a valid UUIDv7 and ``strict`` is set.
    """
    candidate: UUID | None = None

    if isinstance(value, UUID):
        candidate = value
    elif isinstance(value, str):
        try:
            candidate = UUID(value)
        except ValueError:
            candidate = None

    if candidate is not None and candidate.version == UUID_VERSION:
        return candidate

    if strict:
        raise ValueError(f"'{value}' is not a valid UUID version 7 identifier")
    return None


def timestamp_ms(identifier: UUID) -> int:
    """Return the millisecond timestamp embedded in a UUIDv7.

    Useful for diagnostics only. Section 9 forbids inferring business meaning
    from identifier order.
    """
    return identifier.int >> 80
