"""initial schema

Revision ID: 4699f8c3f77f
Revises: 
Create Date: 2026-08-02 19:05:06.440978
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa

# Columns use the project's portable type decorators, so autogenerated
# migrations reference them by their full path.
import app.infrastructure.database.types


revision: str = '4699f8c3f77f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('exercise_type', sa.String(length=32), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('equipment', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('primary_muscles', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('secondary_muscles', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('instructions', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_is_supported'), 'exercises', ['is_supported'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_table('foods',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbohydrates_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('serving_size', sa.String(length=64), nullable=False),
    sa.Column('meal_types', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('diet_tags', app.infrastructure.database.types.StringList(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    op.create_index(op.f('ix_foods_slug'), 'foods', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('body_profiles',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('fitness_goal', sa.String(length=32), nullable=False),
    sa.Column('fitness_level', sa.String(length=32), nullable=False),
    sa.Column('problem_areas', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('workout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_profiles_user_id'), 'body_profiles', ['user_id'], unique=True)
    op.create_table('diet_plans',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('diet_preference', sa.String(length=32), nullable=False),
    sa.Column('estimated_calories', sa.Integer(), nullable=False),
    sa.Column('water_target_ml', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_plans_user_id'), 'diet_plans', ['user_id'], unique=False)
    op.create_index('ix_diet_plans_user_status', 'diet_plans', ['user_id', 'status'], unique=False)
    op.create_table('exercise_sessions',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('exercise_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_sessions_user_id'), 'exercise_sessions', ['user_id'], unique=False)
    op.create_index('ix_exercise_sessions_user_started', 'exercise_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_exercise_sessions_user_status', 'exercise_sessions', ['user_id', 'status'], unique=False)
    op.create_table('progress',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('total_exercises', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('last_workout_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_user_id'), 'progress', ['user_id'], unique=True)
    op.create_table('workout_plans',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_status'), 'workout_plans', ['status'], unique=False)
    op.create_index('ix_workout_plans_user_created', 'workout_plans', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('exercise_results',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('exercise_session_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('frame_timestamp', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=True),
    sa.Column('rep_count', sa.Integer(), nullable=False),
    sa.Column('feedback', app.infrastructure.database.types.StringList(), nullable=False),
    sa.Column('metrics', app.infrastructure.database.types.JSONColumn(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_session_id'], ['exercise_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_results_exercise_session_id'), 'exercise_results', ['exercise_session_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('diet_plan_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_plan_id'], ['diet_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_diet_plan_id'), 'meals', ['diet_plan_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('workout_plan_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('exercise_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('hold_seconds', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_plan_id', 'display_order', name='uq_plan_order')
    )
    op.create_index(op.f('ix_workout_exercises_workout_plan_id'), 'workout_exercises', ['workout_plan_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('workout_plan_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index('ix_workout_sessions_user_started', 'workout_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_workout_sessions_user_status', 'workout_sessions', ['user_id', 'status'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('meal_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('food_id', app.infrastructure.database.types.GUID(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index('ix_workout_sessions_user_status', table_name='workout_sessions')
    op.drop_index('ix_workout_sessions_user_started', table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_exercises_workout_plan_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_meals_diet_plan_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_exercise_results_exercise_session_id'), table_name='exercise_results')
    op.drop_table('exercise_results')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_index('ix_workout_plans_user_created', table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_status'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_progress_user_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index('ix_exercise_sessions_user_status', table_name='exercise_sessions')
    op.drop_index('ix_exercise_sessions_user_started', table_name='exercise_sessions')
    op.drop_index(op.f('ix_exercise_sessions_user_id'), table_name='exercise_sessions')
    op.drop_table('exercise_sessions')
    op.drop_index('ix_diet_plans_user_status', table_name='diet_plans')
    op.drop_index(op.f('ix_diet_plans_user_id'), table_name='diet_plans')
    op.drop_table('diet_plans')
    op.drop_index(op.f('ix_body_profiles_user_id'), table_name='body_profiles')
    op.drop_table('body_profiles')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_foods_slug'), table_name='foods')
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_supported'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
